### ISSUE TITLE
drag-race branch paths 

### ISSUE THREAD

**Issue by marghidanu** [PlummersSoftwareLLC/Primes#110]
Honestly, I find the manual classification of the implementations overengineered. Do we need to reflect this in the structure of the project, a markdown table to mark them as faithful/unfaithful should be enough IMHO.

**Comment by rhbvkleef** [comment]
I thought about this, and I agree the directory structure might need to change. The reason I initially went for the current structure, separating each category, is because a single person might make multiple contributions in different categories. We might decide to drop it down to one category: `stl-faithful`, and only keep those solutions.

A thing I´ve been contemplating is how to deal with parallelized solutions. I think that in the end, we would still need to have some categories. I agree it might be sensible to significantly reduced them. This is what I am thinking of:

* `faithful`
* `parallel`
* `unfaithful` (this would bucket together everything of `stl-unfaithful`, `dependencies-faithful`, `dependencies-unfaithful`, `native`, and any unfaithful parallel implementations)

I think we would still need to keep all these solutions in separate subdirectories, because it is conceivable that people might want to take part in all of these categories.

**Comment by Kinematics** [comment]
Does there even need to be directory structure branching?  Why not just use a proper class-per-file approach, and have commandline switches to indicate which class to target? (Going along with the suggested commandline switches for single-threaded vs multi-threaded runs, and potentially linear vs parallelized versions.)

**Comment by micwoj92** [comment]
I think best one would be per language directories and then inside there whether its faitful or not.

**Comment by rhbvkleef** [comment]
> I think best one would be per language directories and then inside there whether its faitful or not.

@micwoj92, so you propose two categories?

> Does there even need to be directory structure branching? Why not just use a proper class-per-file approach, and have commandline switches to indicate which class to target? (Going along with the suggested commandline switches for single-threaded vs multi-threaded runs, and potentially linear vs parallelized versions.)

@Kinematics, I think we do need some separation, because doing a command-line switch on whether or not to be faithful might not be possible with some languages, as the unfaithful solution might have additional dependencies. Althoug... perhaps those dependencies could just be installed and not used.

**Comment by micwoj92** [comment]
So now since there are also multithreaded options I am not 100% sure. But I still think it would be best if it looked something like this,
directory layout in root folder per language implementation, so let's say python, haskell, c++, autoit3 etc. And in there just faithful single thread, then multi thread and third folder for whatever different implementation someone might think of. I think that per language separation at the top level is best.

OR
Just only accept faithful and multithread, but then I think that for example python numpy should be considered different category than plain python.

**Comment by rhbvkleef** [comment]
I had a discussion with @marghidanu about this, and we agree that this categorization using directories is problematic. As such, we decided to go for a single sub-level below the languages, just numbering each solution. The first CI implementation likely will not support outputting multiple test-results for each implementation, but the output format has been adjusted to allow for that in the future.

**Comment by marghidanu** [comment]
Yep, the CI is a bit more versatile now.

**Comment by rbergen** [comment]
I think we can close this. @rhbvkleef , @marghidanu?

**Comment by marghidanu** [comment]
Fine with me :)
