### ISSUE TITLE
Possibly incorrect bits reported by zig solution 2

### ISSUE THREAD

**Issue by tjol** [PlummersSoftwareLLC/Primes#323]
I noticed that zig solution 2 (`ManDeJan&ityonemo-zig-byte-sieve-type-bool`) is by far the fastest solution reported as base, faithful=yes, bits=1. So I went looking where the magic is, and all I found was an array of `bool`. This could be a packed bit array, but it often isn't. I see this came up in #241, where @ityonemo reported (https://github.com/PlummersSoftwareLLC/Primes/pull/241#issuecomment-861691078) that they're just using `@bitSizeOf`. Sounds fair, but I couldn't find any evidence (in docs, or wherever) that zig uses packed bit arrays by default, so I thought I'd see if I can figure it out by writing a simple test program.

To cut a long story short, this program:

```zig
const std = @import("std");
pub fn main() !void {
    std.debug.print("@sizeOf(u8): {d}\n", .{@sizeOf(u8)});
    std.debug.print("@sizeOf([16]u8): {d}\n", .{@sizeOf([16]u8)});
    std.debug.print("@sizeOf(bool): {d}\n", .{@sizeOf(bool)});
    std.debug.print("@sizeOf([16]bool): {d}\n", .{@sizeOf([16]bool)});
    std.debug.print("@bitSizeOf(u8): {d}\n", .{@bitSizeOf(u8)});
    std.debug.print("@bitSizeOf([16]u8): {d}\n", .{@bitSizeOf([16]u8)});
    std.debug.print("@bitSizeOf(bool): {d}\n", .{@bitSizeOf(bool)});
    std.debug.print("@bitSizeOf([16]bool): {d}\n", .{@bitSizeOf([16]bool)});
}
```

Produces this output:

```
@sizeOf(u8): 1
@sizeOf([16]u8): 16
@sizeOf(bool): 1
@sizeOf([16]bool): 16
@bitSizeOf(u8): 8
@bitSizeOf([16]u8): 128
@bitSizeOf(bool): 1
@bitSizeOf([16]bool): 16
```

Which makes no sense at all (either `[16]bool` is 16 bits, or it's 16 bytes, not both) This leads me to suspect that
 1. `@bitSizeOf` in zig is either broken or not intended to return the number of bits actually used in memory, and
 2. the zig solution(s) should be classified as bits=unknown

This probably applies to a number of other zig solutions as well. They're obviously still very impressive!
 
Also tagging @ManDeJan as your name is also on the solution :-)

**Comment by rbergen** [comment]
> @bitSizeOf in zig is either broken or not intended to return the number of bits actually used in memory

It could be that it does correctly specify the number of _bits required to contain the data contained in the type tested_. It does take just 1 bit to contain a "yes or no" value, and it takes just 16 bits to contain 16 "yes or no" values. 
That said, what is important in the context of this repo is the number of _bits of memory space claimed per prime flag_. If every required bit is effectively stored in its own byte in memory, then in the context of this project's definitions, the bit count is 8, not 1.

**Comment by rbergen** [comment]
I've opened [a post on the Zig forum](https://zigforum.org/t/sizeof-and-bitsizeof-behaviour-on-booleans/625) to raise this question there. If I get a response that clears up this apparent contradiction, I will post it here. Otherwise, I do think we will have to consider the bit size of the prime candidate flags to be unknown, if the structure used to store them is a bool array.

**Comment by marler8997** [comment]
We discussed this on the Zig discord and this appears to be a bug with `@bitSizeOf`.  Zig apparently does not support "packed arrays" so `@bitSizeOf([16]bool)` should be returning `128`.

I've opened an issue here: https://github.com/ziglang/zig/issues/9328

**Comment by tjol** [comment]
Thanks for your input, @marler8997 

Suggestion for how to proceed with the zig solutions' bit count: (@rbergen @ityonemo @ManDeJan)
I think replacing `@bitSizeOf(Type)` with `8*@sizeOf(Type)` should produce the right result.

**Comment by ityonemo** [comment]
@tjol's solution seems reasonable

**Comment by rbergen** [comment]
@tjol Thank you for bringing this to the surface and proposing the solution for producing the right result

@marler8997 Thank you for providing us with a response form the Zig community so quickly. Please pass that thank you on to everyone else who contributed to clearing this up.

@ityonemo Thank you for responding so quickly. Looking at the Zig solutions in the repo, my conclusion is that the change needs to be applied to both solution_2 and solution_3 (in the latter case because the IntSieve is also run with bool as a type). Shall I put a PR together based on the current repo codebase, so that you can review?

**Comment by ityonemo** [comment]
I'll go ahead and do it, since I have one more optimization I think I can sneak in.

**Comment by rbergen** [comment]
Thank you, I appreciate that. I know you recently opened #312 to modify solution_3, but I would like to ask if you can please open a separate PR for this that is based on the current (merged) codebase. That will allow us to fix this quickly, while we take enough time to properly review #312.

**Comment by rbergen** [comment]
Closing after merge of #312
