### ISSUE TITLE
Where can I view recent results?

### ISSUE THREAD

**Issue by travis-leith** [PlummersSoftwareLLC/Primes#373]
Would it be possible for some sort of GitHub CI automation to produce the results somewhere?

**Comment by rbergen** [comment]
In the technical sense yes, in the meaningful sense no. We can tell by the CI runs that the performance of GitHub Actions varies wildly across runs. That is true to the point that some runs randomly fail due to time-outs that cannot be attributed to anything in the state of the repo itself.

It is for this reason that work is being done to allow those who can execute benchmark runs on their own systems to share the results with others. This is discussed in more detail in a comment I added to #362.

**Comment by travis-leith** [comment]
Ok, good to know.
