### ISSUE TITLE
Decide the status of the fake multithread solutions

### ISSUE THREAD

**Issue by kpym** [PlummersSoftwareLLC/Primes#451]
Some of the present solutions use a single thread solutions that are run in parallel for 5 seconds and then we deduce a fantastic speedup.  I think that this kind of solutions should be considered as `fake-multithread` because if we want to evaluate a single sieve they are not faster then the underlying single thread procedure.

For me it is not clear if the race is for the fastest sieve builder, and we run it for 5 seconds just to make the sampling. Or the race is for the number of times that we can build the sieve in 5 seconds. If we are in the first case all `fake-multithread` should be rejected, but if we are in the second case they are perfectly acceptable.

**Comment by rbergen** [comment]
We're not evaluating a single sieve. We're comparing languages, including the aspect of running things in parallel. In your own words, this is about the number of times that we can build the sieve in 5 seconds.

It's very easy to get bogged down in semantics when discussing this topic, but from the perspective of the drag race, you're either:

- a single-threaded implementation
- using multiple threads to squeeze more performance out of hardware that is capable of running them in parallel.

Whether the latter is done using Amdahl scaling, Gustafson scaling, multi-threading, multi-processing or any other approach is up to the implementer. This is also reflected in the name of the tag we use to mark solutions that do use multiple threads, which is called "parallelism". Within the context of that, we will not further distinguish between different qualifications of "multithreaded-ness" ("fake", or otherwise). 

Having said all of that, in the YouTube video series that is connected to this repo, the actual drag race leaderboard will only consider solutions that use the base algorithm, are faithful, use 1 bit per prime flag and are in fact single-threaded.

**Comment by kpym** [comment]
Ok, I got it. 

Probably the only thing that should be avoided by the 'fake' multithread solutions is to display the average (ns/op) because this do not corresponds to the mean time to build a sieve in this case.
