### ISSUE TITLE
Clarify Drag Race Rules

### ISSUE THREAD

**Issue by alexte** [PlummersSoftwareLLC/Primes#79]
Thanks for this fun project.

Comparing languages and algorythms gives interesting insights.

For better comparabilty we should define a clear drag race finish line.

Currently the runSieve functions returns when the bitfield is built. 
This means algorithms that don't use this field are not comparable.
Or functional languages like haskel would not even start because they don't produce data that is not used.

**My proposal for a defined drag race finish line is that the runSieve function should return the number of primes** every time and the benchmark loop should check the value every time. This would be a well defined task that can easily be checked on every run.

**Comment by rhbvkleef** [comment]
I agree that making up a stricter set of rules is a good idea.

I've already had difficulties assigning categories (namely, determining whether something is faithful or not to the original implementation). My main criterion on faithfulness is whether or not it uses a class or similar construct, which is instantiated separately for each run. According to #10 , it already seems that that rule is not enough to make that determination, so I would be welcome to comments on how we can change that rule, or add one, in order to make that determination.

> **My proposal for a defined drag race finish line is that the runSieve function should return the number of primes**

I am actually inclined to agree with this. Either this, or returning the list of primes.

> Or functional languages like haskel would not even start because they don't produce data that is not used.

There are ways of forcing this.

> the benchmark loop should check the value every time

I disagree. Checking the value each time would make benchmarking unnecessarily complicated or slow. Checking it once should be plenty.

**Comment by alexte** [comment]
It's hard to decide if an implementation is equal or equivalent to Dave's original algorithm.
It might be a matter of taste which algorithm is equivalent enough, and therefor a human decision.

But checking the single value of number primes per run doesn't take time and would at least
validate the work of an arbitrary algorithm. I would not compare all the primes.

For example: currently Dave's algorithm doesn't touch all the primes in range, because 
it stops the sieve at sqrt(sieve_limit). It only touches non primes up to sieve_limit. Counting
the number of primes is good enough for a proof of work, and should be part of the tested algorithm.

Rules could be:
1) Provide a function the calculates the number of primes up to X 
2) Don't reuse results or intermediate data on consecutive runs.
3) call above function and check the result in a loop for 5 seconds
4) if a call doesn't give the correct result the benchmark must fail immediately 
5) show  how often the function was called

**Comment by 1da1a172** [comment]
I'm not clear on something even more basic.

> 1. Provide a function the calculates the number of primes up to X

The language here is ambiguous on if it should include X. [[1](https://english.stackexchange.com/questions/16017/how-do-you-interpret-up-to)]

- In the video at 2:09, Dave says "calculate all the prime numbers under 1000".
- At 2:30, he uses ambiguous language similar to rule 1.
- In the C++ implementation (commit ecbedef):
  - In the `printResults` method (line 85) includes it:
    `for (int num = 3; num <= sieveSize; num+=2)`
  - But the equivalent bit of code in the `countPrimes` method (line 111) doesn't (nor does the rest of the code):
    `for (int i = 3; i < sieveSize; i+=2)`

**Comment by rhbvkleef** [comment]
Let´s include it. I believe this was seen as a bug.

**Comment by rbergen** [comment]
Closing this. The drag race rules (and recognized variations) have now been discussed in #218, aligned with @davepl and described in the contributing guidelines.
