### ISSUE TITLE
Rust solution 1 takes 10 seconds instead of just 5

### ISSUE THREAD

**Issue by ghost** [PlummersSoftwareLLC/Primes#857]
I was running random tests and I noticed that Rust solution 1 takes 10 seconds for each test instead of just 5, even though the test reports 5 seconds.

Here is a video of me timing it myself with a stopwatch.
[2022-08-17 00-35-14.mkv.gz](https://github.com/PlummersSoftwareLLC/Primes/files/9356403/2022-08-17.00-35-14.mkv.gz)

**Comment by rbergen** [comment]
This is because the code allows the CPU to cool down for 5 seconds before every test run. Please refer to [lines 952 and 953  in main.rs](https://github.com/PlummersSoftwareLLC/Primes/blob/f8c1a88a008ab72632437130770e0174715ab7b7/PrimeRust/solution_1/prime-sieve-rust/src/main.rs#L952). We allow a run prep of max 5 seconds (either cool-down or warm-up) before every run.
